version: "3"

services:

   traefik:
      image: traefik:v1.7.13
      container_name: traefik
      command: --api --docker
      restart: always
      networks:
         - web
      ports:
         - "80:80"
         - "443:443"
         - "8080:8080"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./traefik.toml:/etc/traefik/traefik.toml
         - ./rules_external.toml:/etc/traefik/rules_external.toml
         - ./ssl/acme.json:/acme.json
         - ./logs/access.log:/access.log
      labels:
         - "traefik.frontend.rule=Host:traefik.petitstores.com"
         - "traefik.port=8080"
         - "traefik.enable=true"

   whoami:
    image: containous/whoami
    labels:
      - traefik.frontend.rule=Host:whoami.petitstores.com 
    networks:
     - web

networks:
  web:
    external: true
